### ISSUE TITLE
On returning products

### ISSUE THREAD

**Issue by dalcde** [hoodmane/rust_ext#28]
We should return the actual product (with coefficients) of two elements instead of just reporting whether xy has a non-zero z-coefficient. The function `add_structline` should probably be renamed to `add_product`

**Comment by hoodmane** [comment]
Eventually we're going to be able to return toda brackets too, but it would be fine to return those with a function called "add_product". Everything is dualized (because we're taking ext in modules not in comodules) so we evaluate x^(z) and find the collection of all elements (y, c) such that x * y = cz + other stuff all at once. Are you suggesting reporting each component of the product separately (x, y, z, c)? 

If we calculate the full matrix x^ : (s, t) + |x| --> (s,t) all together and then transpose it that gives the matrix x : (s, t) --> (s, t) + |x|. Then I could store that in the WASM.

I'm not sure whether sending the coefficient to javascript is that helpful though. If we store the *x matrices in WASM memory, the javascript can send queries if it needs to know more.

**Comment by dalcde** [comment]
I'm still thinking of the case where we are computing Ext(M, k), in
which case the cohomology group is the dual of the group of generators.
So an element in Ext can be represented by an array telling us the value
of each generator, and I'm suggesting we report this array. This is
messier when we compute Ext(M, N) but the same principle should work.

I would like to be able to propagate differentials in the spectral
sequence, so the javascript ought to know some information of this form.

**Comment by hoodmane** [comment]
I think that the right way to do this is to ask the WASM to propagate differentials. Otherwise we'll need to reimplement a bunch of vector operations in javascript when we have perfectly good vector operations in Rust already.

**Comment by dalcde** [comment]
How exactly do you plan to do that? I do not a strategy better than
reimplementing vector operations in javascript. I think that wouldn't be
too bad because nothing there is memory or cpu critical.

**Comment by hoodmane** [comment]
Well a differential E_{x,y} --> E_{x-1,y+h} is represented by a matrix. Suppose d(x) = y and d(x') = y' and you want WASM to compute d(xx') = d(x)y' + xd(y'). If you hand it the matrix representation of the differentials it can compute the relevant products and return the answer.

I was actually considering having the user input the matrix representation of a differential, having the UI hand it to WASM and have WASM respond with the info that javascript needs to adjust the display (dimensions of kernel and cokernel? where to draw lines?) Since we already have perfectly good rust code to compute kernels and cokernels of matrices, I see no reason to reimplement all of that in javascript. My thinking was that the javascript is for controlling the UI and displaying things and the Rust for all the matrix-related code.

Eventually it might be nice to set up Smith Normal Form in Rust and integral matrices in Rust too and then we could handle spectral sequences that are not Fp vector spaces. Achim Krause has implemented that sort of thing before.

**Comment by dalcde** [comment]
In any case I don't think we can use js_spectralsequences as is. One
thing we can do is to implement a version of Sseq.js that reads data
from the rust backend via AJAX.
