### ISSUE TITLE
Running `compute_basis` multiple times on AdemAlgebra at p = 3 crashes

### ISSUE THREAD

**Issue by dalcde** [hoodmane/rust_ext#42]
You have to run it 3-4 times before it crashes. This causes the most recently added test to fail.

You can also observe this by using "resolve further" in the websocket interface.

**Comment by hoodmane** [comment]
Yeah, this is an issue about partially computed content in the multiplication table, similar to the resolve_further issue with kernels. The multiplication table computes P^n * admissible sequence and beta * P^n * admissible sequence at the same time, so that P^n * adm sequence goes into the degree d part and b P^n goes into the degree d + 1 part.

This complicates the logic a lot and could be gotten rid of. Instead, when computing the degree n multiplication table, it should first fill in beta * all of the degree d - 1 things, then run the current generate_multiplication_table_generic_step function generating only P^n * stuff.

Note that it is necessary that you generate the beta P^n * stuff for degree d before the P^n * stuff products in degree d because sometimes the latter kind of products depend on the former kind.

**Comment by hoodmane** [comment]
Wait I'm actually pretty confused about "you have to run it 3-4 times before it crashes." That's really weird. The change I suggested will probably fix the issue, but I have no idea what causes a bug with those particular symptoms.

**Comment by dalcde** [comment]
What exactly does the multiplication table store?

**Comment by hoodmane** [comment]
The multiplication table stores precomputed products of a square by an admissible sequence. So it stores the values of beta^{epsilon} P^n * (some basis element). This way multiplying two admissible sequences happens in as many steps as the length of the left admissible sequence.

I decided that keeping a full lookup table for basis element x basis element --> product is too space hungry because it takes about dimension ^ 3 space. This multiplication table speeds up reducing admissibile sequences a lot and takes degree * dimension^2 space.
