### ISSUE TITLE
The algorithm for resolving chain complexes does not produce the minimal resolution

### ISSUE THREAD

**Issue by dalcde** [hoodmane/rust_ext#44]
For example, I believe if you resolve the chain complex 0 -> A -> A -> 0, you get the same chain complex back, whereas the minimal resolution would be zero. We need to use the minimal resolution or else the generators will not correspond to cohomology classes.

**Comment by hoodmane** [comment]
The condition for the current algorithm to work is that the input complex should have C \otimes_{A} k has a zero differential. This kind of input is a little stupid, and the main application for resolving a chain complex is the modified ASS in which case you would never run into this situation. 

My feeling is that we should just document the condition that to get good output, the differential on C \otimes_{A} k should be zero since I don't really see a use case for the exception to that anyways.
