### ISSUE TITLE
OnceVec is unsound

### ISSUE THREAD

**Issue by dalcde** [hoodmane/rust_ext#92]
Pushing may cause reallocation, so old references may become null pointers. Possibly the cause of #84

**Comment by hoodmane** [comment]
Here's one idea to fix: make the OnceVec into a sequence of "slabs" which are of a fixed page size. When a slab runs out, allocate a new slab and push into next slab. To index, divide index by slab size to pick appropriate slab, index slab by remainder. 

Since the total memory that can be stored is the product of the size of the slab with the length of the slab list, we should pretty easily be able to pick a static length of the slab list and slab size so that filling the data structure would take more memory than we have available.

**Comment by hoodmane** [comment]
Here's a code segment that produces the bug:

        let v = OnceVec::new();
        v.push(vec![0]);
        let firstvec : &Vec<i32> = &v[0usize];
        println!("firstvec[0] : {} firstvec_addr: {:p}", firstvec[0], firstvec as *const Vec<i32>);
        let mut address : *const Vec<i32> = &v[0usize];
        for i in 0 .. 1028*500 {
            if address != &v[0usize] {
                address = &v[0usize];
                println!("moved. i: {}. New address: {:p}", i, address);
            }
            v.push(vec![i]);
        }
        println!("old_addr: {:p}", firstvec as *const Vec<i32>);
        println!("new_addr: {:p}", &v[0usize] as *const Vec<i32>);

        println!("Next line segfaults:");
        println!("{}", firstvec[0]);

**Comment by hoodmane** [comment]
I think I fixed it.
